name: Trivy - AWS Issues

on: [push, pull_request, workflow_dispatch]

jobs:
  terraform:
    name: Trivy AWS Terraform
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          hide-progress: false
          #format: 'sarif'
          #output: 'trivy-results.sarif'
          #ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          scan-ref: 'demo3/aws/terraform_issues'

      # To send scan results to GitHub Security tab change format to 'sarif'
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
