name: GitHub Secrets - Example Using Secrets in Actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    name: Demo Using Secrets
    steps:
    - name: Echo Out The Secret
      env:
        demo1_secret: ${{ secrets.demo_secret }}
      run: echo "$demo1_secret"
